### ISSUE TITLE
Server Error when trying to validate a particular IPOS

### ISSUE THREAD

**Issue by AdityaPrasadMishra** [yochan-lab/iPass-MasterPlan#7]
## Description ->
Getting a server error when trying to validate a particular IPOS. It could be happening with multiple IPOS. Will update as I find it again.

## Pictures  ->
![bug0702](https://user-images.githubusercontent.com/13311691/45003092-60917980-af93-11e8-89f4-da3d81b1643a.png)
![bug0702](https://user-images.githubusercontent.com/13311691/45002974-ee6c6500-af91-11e8-9da4-f1bee6916268.png)

## Server Stack trace ->
While Calling  ### GET /validate?plan=

```
Traceback (most recent call last):
  File "/home/local/ASUAD/amishr28/.local/lib/python2.7/site-packages/flask/app.py", line 2309, in __call__
    return self.wsgi_app(environ, start_response)
  File "/home/local/ASUAD/amishr28/.local/lib/python2.7/site-packages/flask/app.py", line 2295, in wsgi_app
    response = self.handle_exception(e)
  File "/home/local/ASUAD/amishr28/.local/lib/python2.7/site-packages/flask/app.py", line 1741, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/local/ASUAD/amishr28/.local/lib/python2.7/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/local/ASUAD/amishr28/.local/lib/python2.7/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/local/ASUAD/amishr28/.local/lib/python2.7/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/local/ASUAD/amishr28/.local/lib/python2.7/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/local/ASUAD/amishr28/.local/lib/python2.7/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/local/ASUAD/amishr28/iPass-MasterPlan/app.py", line 41, in validate
    planner.get_validated_plan(ui_to_pddl_actions(request, is_get_request=True))
  File "/home/local/ASUAD/amishr28/iPass-MasterPlan/app.py", line 25, in ui_to_pddl_actions
    return translator.uiToActions(plan)
  File "/home/local/ASUAD/amishr28/iPass-MasterPlan/interface.py", line 110, in uiToActions
    action_list = self.__get_action_name(action['name'])
  File "/home/local/ASUAD/amishr28/iPass-MasterPlan/interface.py", line 130, in __get_action_name
    return [str(x) for x in self.__converter(actionType, act[1])]
  File "/home/local/ASUAD/amishr28/iPass-MasterPlan/interface.py", line 154, in __converter
    return func(action, name)
  File "/home/local/ASUAD/amishr28/iPass-MasterPlan/interface.py", line 231, in __addCourse
    self.num[self.sem_counter] + self.connector +\
IndexError: list index out of range
```

## Expected Solution ->
There should not be any server error while validating or submitting iPOS.

**Comment by sachingrover211** [comment]
This is fixed and it wont be happening now. But we need to handle the bad operator case.

**Comment by sailik1991** [comment]
I already had code in place to generate an alert when server error happens on the UI side. Is that showing up? Asking this because the UI image does not show the alert pop-up.

Code: https://github.com/yochan-lab/iPass-MasterPlan/blob/519902a2f48d4f15e6803b4454be1ebef14b98ac/templates/plan.html#L136

**Comment by sailik1991** [comment]
Will look into the `bad operator` case for now.

This happens when some action name from the UI is messed up after conversion to PDDL. For example, if user adds fifteen courses, `interface.py` generated actions with suffix `_ELEVEN_TWELVE` which are not valid actions in the domain.

Any idea on what to report back to the user here? Since Validate will not report back any useful information other than `bad operator`?

**Comment by TathagataChakraborti** [comment]
This is a generic fail case, val reports invalid and nothing more. (for anything that fails in the backend in general)

**Comment by sailik1991** [comment]
Thanks. Will work on this.

**Comment by sailik1991** [comment]
Please check the fix and let me know if this works.

**Comment by AdityaPrasadMishra** [comment]
The fix has still not worked

**Comment by AdityaPrasadMishra** [comment]
Original issue at interface end {https://github.com/yochan-lab/iPass-MasterPlan/issues/7#issuecomment-418217373} is not fixed. Please see the pictures and stack trace below.
## Pictures ->
![bug0201](https://user-images.githubusercontent.com/13311691/45057723-42875000-b04b-11e8-9303-d89f59b16d72.png)
![bug1003](https://user-images.githubusercontent.com/13311691/45057724-42875000-b04b-11e8-9771-15ee0d601993.png)
![bug1005](https://user-images.githubusercontent.com/13311691/45057725-42875000-b04b-11e8-92ff-65cddea8f1a4.png)
![bug1006](https://user-images.githubusercontent.com/13311691/45057726-42875000-b04b-11e8-838d-48429390ba3a.png)

## Stack Trace ->
```
Traceback (most recent call last):
  File "/home/local/ASUAD/amishr28/.local/lib/python2.7/site-packages/flask/app.py", line 2309, in __call__
    return self.wsgi_app(environ, start_response)
  File "/home/local/ASUAD/amishr28/.local/lib/python2.7/site-packages/flask/app.py", line 2295, in wsgi_app
    response = self.handle_exception(e)
  File "/home/local/ASUAD/amishr28/.local/lib/python2.7/site-packages/flask/app.py", line 1741, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/local/ASUAD/amishr28/.local/lib/python2.7/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/local/ASUAD/amishr28/.local/lib/python2.7/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/local/ASUAD/amishr28/.local/lib/python2.7/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/local/ASUAD/amishr28/.local/lib/python2.7/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/local/ASUAD/amishr28/.local/lib/python2.7/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/local/ASUAD/amishr28/iPass-MasterPlan/app.py", line 41, in validate
    is_plan_valid = planner.get_validated_plan(ui_to_pddl_actions(request, is_get_request=True))
  File "/home/local/ASUAD/amishr28/iPass-MasterPlan/app.py", line 25, in ui_to_pddl_actions
    return translator.uiToActions(plan)
  File "/home/local/ASUAD/amishr28/iPass-MasterPlan/interface.py", line 129, in uiToActions
    action_list = self.__get_action_name(action['name'])
  File "/home/local/ASUAD/amishr28/iPass-MasterPlan/interface.py", line 150, in __get_action_name
    return [str(x) for x in self.__converter(actionType, act[1])]
TypeError: 'NoneType' object is not iterable
```

**Comment by AdityaPrasadMishra** [comment]
The above issue is fixed now. Closing issue.
